# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Toddy Mladenov <toddysm@crimsonpinnacle.com>

# Copy custom configuration file from the sub-directory
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80