# Set nginx base image
FROM ubuntu

# File Author / Maintainer
MAINTAINER Toddy Mladenov <toddysm@crimsonpinnacle.com>

# Copy custom configuration file from the sub-directory
RUN apt-get update
RUN apt-get -y install curl
