version: '2'
services:
    nginx:
        build:
            context: .
            dockerfile: nginx
        links:
            - tornado1:tornado1
            - tornado2:tornado2
        ports:
            - "${WEB_PORT}:80"
    tornado1:
        build:
            context: .
            dockerfile: tornado
        ports:
            - "8089"
        env_file:
            - app.env
    tornado2:
        build:
            context: .
            dockerfile: tornado
        ports:
            - "8089"
        env_file:
            - app.env